In [ ]:
Python Installation:
1. check for python installation = python --version
2. if not install then install using = sudo dnf install python3
Jupyter installations:
3. install pip if not already = sudo dnf install python3-pip
4. check for jupyter installation = jupyter --version
5. if not install then install using = sudo pip3 install jupyter
 Run jupyter using = jupyter notebook --allow-root

In [ ]:
Libraries for data science :
1. NumPy = Used for numerical computations. It provides fast arrays, matrices, and mathematical functions.
2. Pandas = Used for data manipulation and analysis. It works with tables (DataFrames) to clean, filter, and organize data.
3. Matplotlib = Used for creating basic graphs and charts like line, bar, scatter, and pie charts.
4. Seaborn = A statistical data visualization library built on Matplotlib. It creates attractive and informative graphs.
5. Scikit-learn (sklearn) = Used for machine learning tasks such as classification, regression, clustering, and model evaluation.
6. SciPy = Used for scientific and mathematical computations like optimization, statistics, and linear algebra.

In [ ]:
How to install libraries :
 1. pip install numpy 
You can install them together as well :
2. pip install numpy pandas matplotlib seaborn scipy scikit-learn keras tensorflow... and so on

In [ ]:
practice Questions

In [7]:
#1.import the Pandas library =
import pandas as pd

In [8]:
#2.how we craete DataFrame? = 
import pandas as pd

data = {
    "Name": ["Amit", "Neha"],
    "Age": [20, 21]
}

df = pd.DataFrame(data)

print(df)

   Name  Age
0  Amit   20
1  Neha   21

In [9]:
#3. how we create series =
import pandas as pd

s = pd.Series([10, 20, 30, 40])

print(s)

0    10
1    20
2    30
3    40
dtype: int64

In [5]:
#4.Create dataframe using numpy array =
import numpy as np
import pandas as pd
data = np.array([['Tata','Nexon',2017],
['MG','Astor',2021],
['KIA','Seltos', 2019],
['Hyundai','Creta',2015]])
df = pd.DataFrame(data, columns = ['company', 'model','year'])
df

   company   model  year
0     Tata   Nexon  2017
1       MG   Astor  2021
2      KIA  Seltos  2019
3  Hyundai   Creta  2015

In [10]:
#5. Create dataframe using list =
import pandas as pd
data = [['Tata','Nexon',2017],['MG','Astor',2021],['KIA','Seltos', 2019],['Hyundai','Creta',2015]]
df = pd.DataFrame(data, columns = ['company', 'model','year'])
# print the dataframe.
df

   company   model  year
0     Tata   Nexon  2017
1       MG   Astor  2021
2      KIA  Seltos  2019
3  Hyundai   Creta  2015

In [11]:
#6. Create dataframe using dictionary with lists =
import pandas as pd
data = {'company': ['Tata','MG','KIA','Hyundai'],
'model':['Nexon','Astor','Seltos','Creta'],
'year': [2017,2021,2019,2015]
}
df = pd.DataFrame.from_dict(data)
df

   company   model  year
0     Tata   Nexon  2017
1       MG   Astor  2021
2      KIA  Seltos  2019
3  Hyundai   Creta  2015

In [12]:
#7. Create dataframe using list of dictionary =
import pandas as pd
data = [{'company':'Tata','model':'Nexon','year':2017},
{'company':'MG','model':'Astor','year':2021},
{'company':'KIA','model':'Seltos','year':2019},
{'company':'Hyundai','model':'Creta','year':2015}]
df = pd.DataFrame(data)
df

   company   model  year
0     Tata   Nexon  2017
1       MG   Astor  2021
2      KIA  Seltos  2019
3  Hyundai   Creta  2015

In [13]:
#8. Create empty dataframe and add records =
import pandas as pd
df = pd.DataFrame(columns = ['company','model','year'])
df.loc[0] = ['Tata', 'Nexon', 2017]
df.loc[1] = ['MG', 'Astor', 2021]
df.loc[2] = ['KIA', 'Seltos', 2019]
df.loc[3] = ['Hyundai', 'Creta', 2015]
df

   company   model  year
0     Tata   Nexon  2017
1       MG   Astor  2021
2      KIA  Seltos  2019
3  Hyundai   Creta  2015

In [14]:
#9. display the first 5 rows of a DataFrame =
print(df.head())

   company   model  year
0     Tata   Nexon  2017
1       MG   Astor  2021
2      KIA  Seltos  2019
3  Hyundai   Creta  2015

In [15]:
#10.display the last 5 rows of a DataFrame =
print(df.tail())

   company   model  year
0     Tata   Nexon  2017
1       MG   Astor  2021
2      KIA  Seltos  2019
3  Hyundai   Creta  2015

In [16]:
#11.check the shape of a DataFrame =
print(df.shape)

(4, 3)

In [17]:
#12. display the column names =
print(df.columns)

Index(['company', 'model', 'year'], dtype='object')

In [18]:
#13.data types of each column =
print(df.dtypes)

company    object
model      object
year        int64
dtype: object

In [19]:
#14. get information about a DataFrame =
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   company  4 non-null      object
 1   model    4 non-null      object
 2   year     4 non-null      int64
dtypes: int64(1), object(2)
memory usage: 96.0+ bytes

In [20]:
#15. view statistical information =
print(df.describe())

              year
count     4.000000
mean   2018.000000
std       2.581989
min    2015.000000
25%    2016.500000
50%    2018.000000
75%    2019.500000
max    2021.000000

In [22]:
#16.select a single column =
print(df["company"])

0       Tata
1         MG
2        KIA
3    Hyundai
Name: company, dtype: object

In [24]:
#17.select multiple columns =
print(df[["model", "year"]])

    model  year
0   Nexon  2017
1   Astor  2021
2  Seltos  2019
3   Creta  2015

In [26]:
#18. select a row using its index =
print(df.loc[0])

company     Tata
model      Nexon
year        2017
Name: 0, dtype: object

In [28]:
#19. add a new column =
df["City"] = ["Pune", "Mumbai","Nagpur","Delhi"]

print(df)

   company   model  year    City
0     Tata   Nexon  2017    Pune
1       MG   Astor  2021  Mumbai
2      KIA  Seltos  2019  Nagpur
3  Hyundai   Creta  2015   Delhi

In [30]:
#20.rename a column =
df.rename(columns={"City": "Company_City"}, inplace=True)

print(df)

   company   model  year Company_City
0     Tata   Nexon  2017         Pune
1       MG   Astor  2021       Mumbai
2      KIA  Seltos  2019       Nagpur
3  Hyundai   Creta  2015        Delhi

In [33]:
#21.delete a column =
df.drop("Company_City", axis=1, inplace=True)

print(df)

   company   model  year
0     Tata   Nexon  2017
1       MG   Astor  2021
2      KIA  Seltos  2019
3  Hyundai   Creta  2015

In [35]:
#22.count the number of rows =
print(len(df))

4

In [36]:
#23. check for missing values =
print(df.isnull())

   company  model   year
0    False  False  False
1    False  False  False
2    False  False  False
3    False  False  False

In [37]:
#24. count missing values =
print(df.isnull().sum())

company    0
model      0
year       0
dtype: int64

In [38]:
#25.remove rows containing missing values =
df = df.dropna()

print(df)

   company   model  year
0     Tata   Nexon  2017
1       MG   Astor  2021
2      KIA  Seltos  2019
3  Hyundai   Creta  2015

In [39]:
#26.replace missing values =
df.fillna(0, inplace=True)

print(df)

   company   model  year
0     Tata   Nexon  2017
1       MG   Astor  2021
2      KIA  Seltos  2019
3  Hyundai   Creta  2015

In [40]:
#27. check for duplicate rows =
print(df.duplicated())

0    False
1    False
2    False
3    False
dtype: bool

In [41]:
#28. count duplicate rows =
print(df.duplicated().sum())

0

In [42]:
#29.remove duplicate rows =
df = df.drop_duplicates()

print(df)

   company   model  year
0     Tata   Nexon  2017
1       MG   Astor  2021
2      KIA  Seltos  2019
3  Hyundai   Creta  2015

In [44]:
#30.sort a DataFrame =
df = df.sort_values("year")

print(df)

   company   model  year
3  Hyundai   Creta  2015
0     Tata   Nexon  2017
2      KIA  Seltos  2019
1       MG   Astor  2021

In [45]:
#31. filter rows =
print(df[df["year"] > 2020])

  company  model  year
1      MG  Astor  2021

In [46]:
#32. save a DataFrame to a CSV file =
df.to_csv("students.csv", index=False)

In [47]:
#33. read a CSV file =
df = pd.read_csv("students.csv")

print(df)

   company   model  year
0  Hyundai   Creta  2015
1     Tata   Nexon  2017
2      KIA  Seltos  2019
3       MG   Astor  2021